language: python
python:
- '2.7'
install:
- pip install .
script: nosetests
deploy:
  provider: openshift
  user: jukka.kinnunen@iki.fi
  password:
    secure: aWezURH5I019kDVwyeVEZBrTW03GZeNLQU6BUHRm7Xy+D0P9ZNrdTwDYLeMhR+pBkYHqqwnVnv46gQzEFDSXMPHqAkbhMVTxbAifnGKBRt4dZfZIEksSjyEcsqPq45UBn2JJ4B6sS4itsyzQFj5xO3qZT1rHQVNI9l6vVfn8v6SybKRZhgxDJqRlbCQPyg08DDGJHsfASOMsfN4GLoLiTB7Afqxh/2fiExaX3XlocX4jZlXFhV9HA+g6LPPVhzLkBuvsJL7ODDLr0DN2Mw/eGXY6nbrCDVJxoYEDjRz5GYZaq4D2H6cXFRhcupl7rvIzy1UfQsO4vcISiARYRb9XuGh5T9vFwmEh9nqSUuZE1lNtQeAmz0+DET+6rNZOv2RCjDA1dRN6tCMt4TJeV34B6Jw8VqKCcbCUc3iXBy149/QUJDllHaK7gcl5hmz6wExtRvxuQhYAy4TTcH4SMPrrz7azW6mNu2JN/whTGgLY6m+QbU2ymGuU3oao0NXDlpIUgxsKsnHlfaIqExiKGiO84ww78GGu4rvD6AR7WIYOpUNV9YJLtd4CcqKCSv54BWi1ofrj21y4f7BtmOy/tSdv9ECo5BdLCYuPOSqibSkfAhvwbUeqqZOP+AxqiNmAVdex1YYvkpohw+kS1FBYO22hNHPFARD6PyqeL+KO4XcU3Ms=
  app: python27004
  domain: jk1
  on:
    repo: resutoor/flask-base
